name: Packs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list-packs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(ls packs/*.csv | jq -R -s -c 'split("\n")[:-1]')"  >> "$GITHUB_OUTPUT"
  run_emulations:
    needs: list-packs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack: ${{ fromJson(needs.list-packs.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run emulations
        run: |
          python top_trumps.py --pack ${{ matrix.pack }}
