name: Number of players

on:
  push:
    branches:
      - main

jobs:
  run_emulations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack: ["packs/elements.csv","packs/mcdonalds-baby-animals.csv","packs/the-art-game.csv"]
        players: [2, 3, 5, 7, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run emulations
        run: |
          python top_trumps.py --pack ${{ matrix.pack }} --number_of_players ${{ matrix.players }} >> $GITHUB_STEP_SUMMARY
