name: Strategies

on:
  push:
    branches:
      - main

jobs:
  run_emulations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack: ["packs/elements.csv","packs/mcdonalds-baby-animals.csv","packs/the-art-game.csv"]
        strategy: ['get_highest_stat_index', 'get_random_stat_index']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run emulations
        run: |
          python top_trumps.py --pack ${{ matrix.pack }} --get_stat_index_method ${{ matrix.strategy }}
